### ISSUE TITLE
C'est quoi un système de contrôle de version ? Et pourquoi je devrais m'intéresser à git, même si je suis seul ?

### ISSUE THREAD

**Issue by statnmap** [r-nantes/meetups#5]
Proposition

- C'est quoi un système de contrôle de version ? Et pourquoi je devrais m'intéresser à git, même si je suis seul ?
    - Swann Flochlay
    - https://github.com/dagousket/meetupr_pres
- Mettez en place vos projets collaboratifs sur GitLab de manière automatisée avec {gitlabr}
    - Sébastien Rochette
    - https://github.com/statnmap/prez/blob/master/2022-11-21_gestion_de_gitlab_automatisee_avec_gitlabr.pdf

=> 29 novembre - 19h - En visio

**Comment by dagousket** [comment]
Partante pour m'y atteler pour le meetUp de décembre, ou plus tard :-)
